spring:
  datasource:
    url: jdbc:mysql://localhost:3306/messagedb
    username: root
    password: litianyu2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    url: redis://user:password@example.com:6379


mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    use-deprecated-executor: false
server:
  servlet:
    context-path: /admin